a = input("enter first text A:")
b = input("enter first text B:")
c = input("enter first text C:")
d = input("enter first text D:")
e = input("enter first text E:")
a = a.replace(" ","")
b = b.replace(" ","")
c = c.replace(" ","")
d = d.replace(" ","")
e = e.replace(" ","")
print("lengh of A= ", len(a), "lengh of B= ", len(b), "lengh of C= ", len(c), "lengh of D= ", len(d), "lengh of E= ", len(e))